// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AI_CancelStream() {
  return window['go']['handlers']['AIHandler']['AI_CancelStream']();
}

export function AI_GenerateStream(arg1) {
  return window['go']['handlers']['AIHandler']['AI_GenerateStream'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['AIHandler']['Startup'](arg1);
}
