// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CleanOldBackups(arg1:number):Promise<number>;

export function CreateBackup():Promise<domain.BackupResult>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DownloadProductsTemplateNative():Promise<boolean>;

export function ExportDatabase():Promise<domain.DatabaseExport>;

export function ExportDatabaseBackupNative():Promise<boolean>;

export function ExportProductsCSV():Promise<domain.CSVExportResult>;

export function ExportProductsCSVNative():Promise<domain.CSVExportResult>;

export function GetCSVTemplate():Promise<string>;

export function GetImageStorageStats():Promise<domain.ImageStorageStats>;

export function ImportDatabase(arg1:domain.DatabaseExport):Promise<void>;

export function ImportDatabaseBackupNative():Promise<boolean>;

export function ImportProductsCSV(arg1:string,arg2:boolean):Promise<domain.CSVImportResult>;

export function ImportProductsCSVNative(arg1:boolean):Promise<domain.CSVImportResult>;

export function ListBackups():Promise<Array<domain.BackupInfo>>;

export function MigrateImagesToFilesystem():Promise<number>;

export function ResetDatabase():Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
