// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanOldBackups(arg1) {
  return window['go']['handlers']['BackupHandler']['CleanOldBackups'](arg1);
}

export function CreateBackup() {
  return window['go']['handlers']['BackupHandler']['CreateBackup']();
}

export function DeleteBackup(arg1) {
  return window['go']['handlers']['BackupHandler']['DeleteBackup'](arg1);
}

export function DownloadProductsTemplateNative() {
  return window['go']['handlers']['BackupHandler']['DownloadProductsTemplateNative']();
}

export function ExportDatabase() {
  return window['go']['handlers']['BackupHandler']['ExportDatabase']();
}

export function ExportDatabaseBackupNative() {
  return window['go']['handlers']['BackupHandler']['ExportDatabaseBackupNative']();
}

export function ExportProductsCSV() {
  return window['go']['handlers']['BackupHandler']['ExportProductsCSV']();
}

export function ExportProductsCSVNative() {
  return window['go']['handlers']['BackupHandler']['ExportProductsCSVNative']();
}

export function GetCSVTemplate() {
  return window['go']['handlers']['BackupHandler']['GetCSVTemplate']();
}

export function GetImageStorageStats() {
  return window['go']['handlers']['BackupHandler']['GetImageStorageStats']();
}

export function ImportDatabase(arg1) {
  return window['go']['handlers']['BackupHandler']['ImportDatabase'](arg1);
}

export function ImportDatabaseBackupNative() {
  return window['go']['handlers']['BackupHandler']['ImportDatabaseBackupNative']();
}

export function ImportProductsCSV(arg1, arg2) {
  return window['go']['handlers']['BackupHandler']['ImportProductsCSV'](arg1, arg2);
}

export function ImportProductsCSVNative(arg1) {
  return window['go']['handlers']['BackupHandler']['ImportProductsCSVNative'](arg1);
}

export function ListBackups() {
  return window['go']['handlers']['BackupHandler']['ListBackups']();
}

export function MigrateImagesToFilesystem() {
  return window['go']['handlers']['BackupHandler']['MigrateImagesToFilesystem']();
}

export function ResetDatabase() {
  return window['go']['handlers']['BackupHandler']['ResetDatabase']();
}

export function RestoreBackup(arg1) {
  return window['go']['handlers']['BackupHandler']['RestoreBackup'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['BackupHandler']['Startup'](arg1);
}
