// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['handlers']['CloudHandler']['ActivateLicense'](arg1);
}

export function AdminLogin(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['AdminLogin'](arg1, arg2);
}

export function CheckLicenseStatus(arg1) {
  return window['go']['handlers']['CloudHandler']['CheckLicenseStatus'](arg1);
}

export function CheckSessionValidity() {
  return window['go']['handlers']['CloudHandler']['CheckSessionValidity']();
}

export function CloudBackupNow() {
  return window['go']['handlers']['CloudHandler']['CloudBackupNow']();
}

export function CompleteGoogleAuth() {
  return window['go']['handlers']['CloudHandler']['CompleteGoogleAuth']();
}

export function CreateLicense(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['CloudHandler']['CreateLicense'](arg1, arg2, arg3, arg4);
}

export function DeleteCloudBackup(arg1) {
  return window['go']['handlers']['CloudHandler']['DeleteCloudBackup'](arg1);
}

export function DeleteCurrentUser() {
  return window['go']['handlers']['CloudHandler']['DeleteCurrentUser']();
}

export function DeleteLicenseRemote(arg1) {
  return window['go']['handlers']['CloudHandler']['DeleteLicenseRemote'](arg1);
}

export function DisableZohoIntegration() {
  return window['go']['handlers']['CloudHandler']['DisableZohoIntegration']();
}

export function DisconnectGoogle() {
  return window['go']['handlers']['CloudHandler']['DisconnectGoogle']();
}

export function ExtendLicense(arg1, arg2, arg3) {
  return window['go']['handlers']['CloudHandler']['ExtendLicense'](arg1, arg2, arg3);
}

export function FetchAdminLogs() {
  return window['go']['handlers']['CloudHandler']['FetchAdminLogs']();
}

export function FetchAllLicenses() {
  return window['go']['handlers']['CloudHandler']['FetchAllLicenses']();
}

export function GetCachedLicense() {
  return window['go']['handlers']['CloudHandler']['GetCachedLicense']();
}

export function GetCurrentUser() {
  return window['go']['handlers']['CloudHandler']['GetCurrentUser']();
}

export function GetLicenseUserDetails(arg1) {
  return window['go']['handlers']['CloudHandler']['GetLicenseUserDetails'](arg1);
}

export function GetStoredLicenseKey() {
  return window['go']['handlers']['CloudHandler']['GetStoredLicenseKey']();
}

export function GetUserLicenseStatus() {
  return window['go']['handlers']['CloudHandler']['GetUserLicenseStatus']();
}

export function GetZohoStatus() {
  return window['go']['handlers']['CloudHandler']['GetZohoStatus']();
}

export function InitGoogleAuth() {
  return window['go']['handlers']['CloudHandler']['InitGoogleAuth']();
}

export function IsGoogleConnected() {
  return window['go']['handlers']['CloudHandler']['IsGoogleConnected']();
}

export function IsLoggedIn() {
  return window['go']['handlers']['CloudHandler']['IsLoggedIn']();
}

export function ListCloudBackupsForUser() {
  return window['go']['handlers']['CloudHandler']['ListCloudBackupsForUser']();
}

export function LogAdminAction(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['CloudHandler']['LogAdminAction'](arg1, arg2, arg3, arg4);
}

export function Login(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['handlers']['CloudHandler']['Logout']();
}

export function RecoverPassword(arg1) {
  return window['go']['handlers']['CloudHandler']['RecoverPassword'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['handlers']['CloudHandler']['Register'](arg1, arg2, arg3);
}

export function ResetLicenseToTrial(arg1) {
  return window['go']['handlers']['CloudHandler']['ResetLicenseToTrial'](arg1);
}

export function RestoreCloudBackup(arg1) {
  return window['go']['handlers']['CloudHandler']['RestoreCloudBackup'](arg1);
}

export function SetMasterKey(arg1) {
  return window['go']['handlers']['CloudHandler']['SetMasterKey'](arg1);
}

export function SetupZohoIntegration(arg1, arg2, arg3) {
  return window['go']['handlers']['CloudHandler']['SetupZohoIntegration'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['handlers']['CloudHandler']['Startup'](arg1);
}

export function UpdateLicenseFeatures(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['UpdateLicenseFeatures'](arg1, arg2);
}

export function UpdateLicenseStatus(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['UpdateLicenseStatus'](arg1, arg2);
}

export function UpdatePaymentStatus(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['UpdatePaymentStatus'](arg1, arg2);
}

export function UploadBackupToDrive(arg1, arg2) {
  return window['go']['handlers']['CloudHandler']['UploadBackupToDrive'](arg1, arg2);
}

export function VerifyLicense(arg1) {
  return window['go']['handlers']['CloudHandler']['VerifyLicense'](arg1);
}
