// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function DeleteCustomer(arg1:string,arg2:boolean):Promise<void>;

export function DeleteSupplier(arg1:string,arg2:boolean):Promise<void>;

export function GetCustomers():Promise<Array<domain.Customer>>;

export function GetSuppliers():Promise<Array<domain.Supplier>>;

export function SaveCustomer(arg1:domain.Customer):Promise<void>;

export function SaveSupplier(arg1:domain.Supplier):Promise<void>;

export function SearchCustomers(arg1:string):Promise<Array<domain.Customer>>;

export function Startup(arg1:context.Context):Promise<void>;
