// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomer(arg1, arg2) {
  return window['go']['handlers']['CRMHandler']['DeleteCustomer'](arg1, arg2);
}

export function DeleteSupplier(arg1, arg2) {
  return window['go']['handlers']['CRMHandler']['DeleteSupplier'](arg1, arg2);
}

export function GetCustomers() {
  return window['go']['handlers']['CRMHandler']['GetCustomers']();
}

export function GetCustomersPaged(arg1, arg2, arg3) {
  return window['go']['handlers']['CRMHandler']['GetCustomersPaged'](arg1, arg2, arg3);
}

export function GetSuppliers() {
  return window['go']['handlers']['CRMHandler']['GetSuppliers']();
}

export function GetSuppliersPaged(arg1, arg2, arg3) {
  return window['go']['handlers']['CRMHandler']['GetSuppliersPaged'](arg1, arg2, arg3);
}

export function SaveCustomer(arg1) {
  return window['go']['handlers']['CRMHandler']['SaveCustomer'](arg1);
}

export function SaveSupplier(arg1) {
  return window['go']['handlers']['CRMHandler']['SaveSupplier'](arg1);
}

export function SearchCustomers(arg1) {
  return window['go']['handlers']['CRMHandler']['SearchCustomers'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['CRMHandler']['Startup'](arg1);
}
