// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function ApplyDiscount(arg1:string):Promise<void>;

export function CreateDiscount(arg1:domain.Discount):Promise<domain.Discount>;

export function DeleteDiscount(arg1:string):Promise<void>;

export function GetActiveDiscounts():Promise<Array<domain.Discount>>;

export function GetAllDiscounts():Promise<Array<domain.Discount>>;

export function GetDiscount(arg1:string):Promise<domain.Discount>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleDiscountStatus(arg1:string):Promise<void>;

export function UpdateDiscount(arg1:domain.Discount):Promise<void>;

export function ValidateCoupon(arg1:string):Promise<domain.Discount>;
