// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDiscount(arg1) {
  return window['go']['handlers']['DiscountHandler']['ApplyDiscount'](arg1);
}

export function CreateDiscount(arg1) {
  return window['go']['handlers']['DiscountHandler']['CreateDiscount'](arg1);
}

export function DeleteDiscount(arg1) {
  return window['go']['handlers']['DiscountHandler']['DeleteDiscount'](arg1);
}

export function GetActiveDiscounts() {
  return window['go']['handlers']['DiscountHandler']['GetActiveDiscounts']();
}

export function GetAllDiscounts() {
  return window['go']['handlers']['DiscountHandler']['GetAllDiscounts']();
}

export function GetDiscount(arg1) {
  return window['go']['handlers']['DiscountHandler']['GetDiscount'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['DiscountHandler']['Startup'](arg1);
}

export function ToggleDiscountStatus(arg1) {
  return window['go']['handlers']['DiscountHandler']['ToggleDiscountStatus'](arg1);
}

export function UpdateDiscount(arg1) {
  return window['go']['handlers']['DiscountHandler']['UpdateDiscount'](arg1);
}

export function ValidateCoupon(arg1) {
  return window['go']['handlers']['DiscountHandler']['ValidateCoupon'](arg1);
}
