// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCashMovement(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handlers']['FinanceHandler']['AddCashMovement'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelPurchaseOrder(arg1) {
  return window['go']['handlers']['FinanceHandler']['CancelPurchaseOrder'](arg1);
}

export function CloseShift(arg1, arg2, arg3) {
  return window['go']['handlers']['FinanceHandler']['CloseShift'](arg1, arg2, arg3);
}

export function CreatePurchaseOrder(arg1) {
  return window['go']['handlers']['FinanceHandler']['CreatePurchaseOrder'](arg1);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['handlers']['FinanceHandler']['DeleteCategory'](arg1, arg2);
}

export function DeleteExpense(arg1) {
  return window['go']['handlers']['FinanceHandler']['DeleteExpense'](arg1);
}

export function DeletePurchaseOrder(arg1) {
  return window['go']['handlers']['FinanceHandler']['DeletePurchaseOrder'](arg1);
}

export function GetActiveShift() {
  return window['go']['handlers']['FinanceHandler']['GetActiveShift']();
}

export function GetCategories() {
  return window['go']['handlers']['FinanceHandler']['GetCategories']();
}

export function GetExpenses() {
  return window['go']['handlers']['FinanceHandler']['GetExpenses']();
}

export function GetPreferences() {
  return window['go']['handlers']['FinanceHandler']['GetPreferences']();
}

export function GetPurchaseOrder(arg1) {
  return window['go']['handlers']['FinanceHandler']['GetPurchaseOrder'](arg1);
}

export function GetPurchaseOrderStats() {
  return window['go']['handlers']['FinanceHandler']['GetPurchaseOrderStats']();
}

export function GetPurchaseOrders(arg1, arg2) {
  return window['go']['handlers']['FinanceHandler']['GetPurchaseOrders'](arg1, arg2);
}

export function GetShiftHistory(arg1) {
  return window['go']['handlers']['FinanceHandler']['GetShiftHistory'](arg1);
}

export function GetShiftMovements(arg1) {
  return window['go']['handlers']['FinanceHandler']['GetShiftMovements'](arg1);
}

export function OpenShift(arg1, arg2, arg3) {
  return window['go']['handlers']['FinanceHandler']['OpenShift'](arg1, arg2, arg3);
}

export function PayPurchaseOrder(arg1, arg2, arg3) {
  return window['go']['handlers']['FinanceHandler']['PayPurchaseOrder'](arg1, arg2, arg3);
}

export function ReceivePurchaseOrder(arg1, arg2) {
  return window['go']['handlers']['FinanceHandler']['ReceivePurchaseOrder'](arg1, arg2);
}

export function SaveCategory(arg1) {
  return window['go']['handlers']['FinanceHandler']['SaveCategory'](arg1);
}

export function SaveExpense(arg1) {
  return window['go']['handlers']['FinanceHandler']['SaveExpense'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['FinanceHandler']['Startup'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['handlers']['FinanceHandler']['UpdatePreferences'](arg1);
}

export function UpdatePurchaseOrder(arg1) {
  return window['go']['handlers']['FinanceHandler']['UpdatePurchaseOrder'](arg1);
}

export function VerifyAdminPin(arg1) {
  return window['go']['handlers']['FinanceHandler']['VerifyAdminPin'](arg1);
}
