// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AddCashMovement(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<domain.CashMovement>;

export function CancelPurchaseOrder(arg1:string):Promise<void>;

export function CloseShift(arg1:string,arg2:number,arg3:string):Promise<domain.Shift>;

export function CreatePurchaseOrder(arg1:domain.PurchaseOrder):Promise<domain.PurchaseOrder>;

export function DeleteCategory(arg1:string,arg2:boolean):Promise<void>;

export function DeleteExpense(arg1:string):Promise<void>;

export function DeletePurchaseOrder(arg1:string):Promise<void>;

export function GetActiveShift():Promise<domain.Shift>;

export function GetCategories():Promise<Array<domain.Category>>;

export function GetExpenses():Promise<Array<domain.Expense>>;

export function GetPreferences():Promise<domain.AppPreferences>;

export function GetPurchaseOrder(arg1:string):Promise<domain.PurchaseOrder>;

export function GetPurchaseOrderStats():Promise<Record<string, any>>;

export function GetPurchaseOrders(arg1:string,arg2:string):Promise<Array<domain.PurchaseOrder>>;

export function GetShiftHistory(arg1:number):Promise<Array<domain.Shift>>;

export function GetShiftMovements(arg1:string):Promise<Array<domain.CashMovement>>;

export function OpenShift(arg1:string,arg2:string,arg3:number):Promise<domain.Shift>;

export function PayPurchaseOrder(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ReceivePurchaseOrder(arg1:string,arg2:Array<domain.PurchaseOrderItem>):Promise<void>;

export function SaveCategory(arg1:domain.Category):Promise<void>;

export function SaveExpense(arg1:domain.Expense):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdatePreferences(arg1:domain.AppPreferences):Promise<void>;

export function UpdatePurchaseOrder(arg1:domain.PurchaseOrder):Promise<void>;

export function VerifyAdminPin(arg1:string):Promise<boolean>;
