// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockLanDevice(arg1, arg2, arg3) {
  return window['go']['handlers']['LanHandler']['BlockLanDevice'](arg1, arg2, arg3);
}

export function ConnectToLanServer(arg1, arg2, arg3) {
  return window['go']['handlers']['LanHandler']['ConnectToLanServer'](arg1, arg2, arg3);
}

export function DisconnectFromLanServer() {
  return window['go']['handlers']['LanHandler']['DisconnectFromLanServer']();
}

export function DisconnectLanClient(arg1) {
  return window['go']['handlers']['LanHandler']['DisconnectLanClient'](arg1);
}

export function DiscoverServers() {
  return window['go']['handlers']['LanHandler']['DiscoverServers']();
}

export function GenerateServerSecret() {
  return window['go']['handlers']['LanHandler']['GenerateServerSecret']();
}

export function GetBlockedDevices() {
  return window['go']['handlers']['LanHandler']['GetBlockedDevices']();
}

export function GetConnectedClients() {
  return window['go']['handlers']['LanHandler']['GetConnectedClients']();
}

export function GetLanClientStatus() {
  return window['go']['handlers']['LanHandler']['GetLanClientStatus']();
}

export function GetLanServerStatus() {
  return window['go']['handlers']['LanHandler']['GetLanServerStatus']();
}

export function GetLocalIP() {
  return window['go']['handlers']['LanHandler']['GetLocalIP']();
}

export function GetServerSecret() {
  return window['go']['handlers']['LanHandler']['GetServerSecret']();
}

export function ResumeLanClient(arg1) {
  return window['go']['handlers']['LanHandler']['ResumeLanClient'](arg1);
}

export function StartLanServer() {
  return window['go']['handlers']['LanHandler']['StartLanServer']();
}

export function Startup(arg1) {
  return window['go']['handlers']['LanHandler']['Startup'](arg1);
}

export function StopLanServer() {
  return window['go']['handlers']['LanHandler']['StopLanServer']();
}

export function SuspendLanClient(arg1) {
  return window['go']['handlers']['LanHandler']['SuspendLanClient'](arg1);
}

export function TestLanConnection() {
  return window['go']['handlers']['LanHandler']['TestLanConnection']();
}

export function UnblockLanDevice(arg1) {
  return window['go']['handlers']['LanHandler']['UnblockLanDevice'](arg1);
}
