// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function BlockLanDevice(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectToLanServer(arg1:string,arg2:number):Promise<void>;

export function DisconnectFromLanServer():Promise<void>;

export function DisconnectLanClient(arg1:string):Promise<void>;

export function DiscoverServers():Promise<Array<domain.DiscoveredServer>>;

export function GenerateServerSecret():Promise<string>;

export function GetBlockedDevices():Promise<Array<domain.BlockedDevice>>;

export function GetConnectedClients():Promise<Array<domain.ConnectedClient>>;

export function GetLanClientStatus():Promise<domain.LanClientStatus>;

export function GetLanServerStatus():Promise<domain.LanServerStatus>;

export function GetLocalIP():Promise<string>;

export function GetServerSecret():Promise<string>;

export function ResumeLanClient(arg1:string):Promise<void>;

export function StartLanServer():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopLanServer():Promise<void>;

export function SuspendLanClient(arg1:string):Promise<void>;

export function TestLanConnection():Promise<string>;

export function UnblockLanDevice(arg1:number):Promise<void>;
