// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {handlers} from '../models';
import {context} from '../models';

export function CalculateInstallmentPlan(arg1:domain.Amount,arg2:domain.Amount,arg3:number):Promise<domain.InstallmentPlan>;

export function CreatePayment(arg1:domain.Payment):Promise<domain.Payment>;

export function DeletePayment(arg1:number):Promise<void>;

export function GetCustomerInstallments(arg1:string):Promise<Array<domain.Sale>>;

export function GetInstallmentSummary(arg1:string):Promise<handlers.InstallmentSummaryResult>;

export function GetPaymentsByCustomer(arg1:string):Promise<Array<domain.Payment>>;

export function GetPaymentsBySale(arg1:string):Promise<Array<domain.Payment>>;

export function PayInstallment(arg1:string,arg2:number,arg3:domain.Amount,arg4:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
