// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateInstallmentPlan(arg1, arg2, arg3) {
  return window['go']['handlers']['PaymentHandler']['CalculateInstallmentPlan'](arg1, arg2, arg3);
}

export function CreatePayment(arg1) {
  return window['go']['handlers']['PaymentHandler']['CreatePayment'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['handlers']['PaymentHandler']['DeletePayment'](arg1);
}

export function GetCustomerInstallments(arg1) {
  return window['go']['handlers']['PaymentHandler']['GetCustomerInstallments'](arg1);
}

export function GetInstallmentSummary(arg1) {
  return window['go']['handlers']['PaymentHandler']['GetInstallmentSummary'](arg1);
}

export function GetPaymentsByCustomer(arg1) {
  return window['go']['handlers']['PaymentHandler']['GetPaymentsByCustomer'](arg1);
}

export function GetPaymentsBySale(arg1) {
  return window['go']['handlers']['PaymentHandler']['GetPaymentsBySale'](arg1);
}

export function PayInstallment(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['PaymentHandler']['PayInstallment'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['handlers']['PaymentHandler']['Startup'](arg1);
}
