// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GenerateInvoicePDF(arg1:string,arg2:string):Promise<string>;

export function GenerateQRCode(arg1:string,arg2:number):Promise<string>;

export function GetAvailablePrinters():Promise<Array<domain.PrinterInfo>>;

export function GetDefaultPrinter():Promise<string>;

export function PrintBitmapReceipt(arg1:string,arg2:string):Promise<void>;

export function PrintReceiptDirect(arg1:string,arg2:string,arg3:Array<domain.ReceiptItem>,arg4:number,arg5:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestPrinter(arg1:string):Promise<void>;
