// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateInvoicePDF(arg1, arg2) {
  return window['go']['handlers']['PrintHandler']['GenerateInvoicePDF'](arg1, arg2);
}

export function GenerateQRCode(arg1, arg2) {
  return window['go']['handlers']['PrintHandler']['GenerateQRCode'](arg1, arg2);
}

export function GetAvailablePrinters() {
  return window['go']['handlers']['PrintHandler']['GetAvailablePrinters']();
}

export function GetDefaultPrinter() {
  return window['go']['handlers']['PrintHandler']['GetDefaultPrinter']();
}

export function PrintBitmapReceipt(arg1, arg2) {
  return window['go']['handlers']['PrintHandler']['PrintBitmapReceipt'](arg1, arg2);
}

export function PrintReceiptDirect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['PrintHandler']['PrintReceiptDirect'](arg1, arg2, arg3, arg4, arg5);
}

export function Startup(arg1) {
  return window['go']['handlers']['PrintHandler']['Startup'](arg1);
}

export function TestPrinter(arg1) {
  return window['go']['handlers']['PrintHandler']['TestPrinter'](arg1);
}
