// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CreateProduct(arg1:domain.Product):Promise<void>;

export function DeleteProduct(arg1:string):Promise<void>;

export function GetAllProducts():Promise<Array<domain.Product>>;

export function GetProductByID(arg1:string):Promise<domain.Product>;

export function GetStockMovements():Promise<Array<domain.StockMovement>>;

export function LogStockMovement(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;

export function SearchProducts(arg1:string):Promise<Array<domain.Product>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateProduct(arg1:domain.Product):Promise<void>;
