// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['handlers']['ProductHandler']['CreateProduct'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['handlers']['ProductHandler']['DeleteProduct'](arg1);
}

export function GetAllProducts() {
  return window['go']['handlers']['ProductHandler']['GetAllProducts']();
}

export function GetProductByID(arg1) {
  return window['go']['handlers']['ProductHandler']['GetProductByID'](arg1);
}

export function GetStockMovements() {
  return window['go']['handlers']['ProductHandler']['GetStockMovements']();
}

export function LogStockMovement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['ProductHandler']['LogStockMovement'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchProducts(arg1) {
  return window['go']['handlers']['ProductHandler']['SearchProducts'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['ProductHandler']['Startup'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['handlers']['ProductHandler']['UpdateProduct'](arg1);
}
