// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function DeleteParkedSale(arg1:number):Promise<void>;

export function DeleteSale(arg1:string):Promise<void>;

export function GetInstallmentSales():Promise<Array<domain.Sale>>;

export function GetParkedSales():Promise<Array<domain.ParkedSale>>;

export function GetParkedSalesCount():Promise<number>;

export function GetSale(arg1:string):Promise<domain.Sale>;

export function GetSaleItems(arg1:string):Promise<Array<domain.SaleItem>>;

export function GetSales(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<domain.PaginatedSales>;

export function ParkSale(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<domain.ParkedSale>;

export function ProcessSale(arg1:domain.Sale):Promise<void>;

export function RetrieveParkedSale(arg1:number):Promise<domain.ParkedSale>;

export function ReturnSale(arg1:string):Promise<void>;

export function ReturnSalePartial(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
