// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteParkedSale(arg1) {
  return window['go']['handlers']['SaleHandler']['DeleteParkedSale'](arg1);
}

export function DeleteSale(arg1) {
  return window['go']['handlers']['SaleHandler']['DeleteSale'](arg1);
}

export function GetParkedSales() {
  return window['go']['handlers']['SaleHandler']['GetParkedSales']();
}

export function GetParkedSalesCount() {
  return window['go']['handlers']['SaleHandler']['GetParkedSalesCount']();
}

export function GetSale(arg1) {
  return window['go']['handlers']['SaleHandler']['GetSale'](arg1);
}

export function GetSaleItems(arg1) {
  return window['go']['handlers']['SaleHandler']['GetSaleItems'](arg1);
}

export function GetSales(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handlers']['SaleHandler']['GetSales'](arg1, arg2, arg3, arg4, arg5);
}

export function ParkSale(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['handlers']['SaleHandler']['ParkSale'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ProcessSale(arg1) {
  return window['go']['handlers']['SaleHandler']['ProcessSale'](arg1);
}

export function RetrieveParkedSale(arg1) {
  return window['go']['handlers']['SaleHandler']['RetrieveParkedSale'](arg1);
}

export function ReturnSale(arg1) {
  return window['go']['handlers']['SaleHandler']['ReturnSale'](arg1);
}

export function ReturnSalePartial(arg1, arg2, arg3) {
  return window['go']['handlers']['SaleHandler']['ReturnSalePartial'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['handlers']['SaleHandler']['Startup'](arg1);
}
