// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CheckForUpdates():Promise<domain.UpdateInfo>;

export function ClearCrashReports():Promise<void>;

export function DisableAutoStart():Promise<void>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function EnableAutoStart():Promise<void>;

export function FetchGlobalAIKeys():Promise<Array<string>>;

export function FetchGlobalGroqKeys():Promise<Array<string>>;

export function GetCrashReportContent(arg1:string):Promise<string>;

export function GetCrashReports():Promise<Array<string>>;

export function GetCurrentVersion():Promise<string>;

export function GetDeviceID():Promise<string>;

export function GetPreferences():Promise<domain.AppPreferences>;

export function GetUpdateStatus():Promise<domain.UpdateStatus>;

export function InstallUpdate(arg1:string):Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function SaveGlobalAIKeys(arg1:Array<string>,arg2:string):Promise<void>;

export function SaveGlobalGroqKeys(arg1:Array<string>,arg2:string):Promise<void>;

export function ShowNativeNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdatePreferences(arg1:domain.AppPreferences):Promise<void>;

export function VerifyAdminPin(arg1:string):Promise<boolean>;
