// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['handlers']['SettingsHandler']['CheckForUpdates']();
}

export function ClearCrashReports() {
  return window['go']['handlers']['SettingsHandler']['ClearCrashReports']();
}

export function DisableAutoStart() {
  return window['go']['handlers']['SettingsHandler']['DisableAutoStart']();
}

export function DownloadUpdate(arg1) {
  return window['go']['handlers']['SettingsHandler']['DownloadUpdate'](arg1);
}

export function EnableAutoStart() {
  return window['go']['handlers']['SettingsHandler']['EnableAutoStart']();
}

export function FetchGlobalAIKeys() {
  return window['go']['handlers']['SettingsHandler']['FetchGlobalAIKeys']();
}

export function GetCrashReportContent(arg1) {
  return window['go']['handlers']['SettingsHandler']['GetCrashReportContent'](arg1);
}

export function GetCrashReports() {
  return window['go']['handlers']['SettingsHandler']['GetCrashReports']();
}

export function GetCurrentVersion() {
  return window['go']['handlers']['SettingsHandler']['GetCurrentVersion']();
}

export function GetDeviceID() {
  return window['go']['handlers']['SettingsHandler']['GetDeviceID']();
}

export function GetPreferences() {
  return window['go']['handlers']['SettingsHandler']['GetPreferences']();
}

export function GetUpdateStatus() {
  return window['go']['handlers']['SettingsHandler']['GetUpdateStatus']();
}

export function InstallUpdate(arg1) {
  return window['go']['handlers']['SettingsHandler']['InstallUpdate'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['handlers']['SettingsHandler']['IsAutoStartEnabled']();
}

export function SaveGlobalAIKeys(arg1, arg2) {
  return window['go']['handlers']['SettingsHandler']['SaveGlobalAIKeys'](arg1, arg2);
}

export function ShowNativeNotification(arg1, arg2, arg3) {
  return window['go']['handlers']['SettingsHandler']['ShowNativeNotification'](arg1, arg2, arg3);
}

export function SkipVersion(arg1) {
  return window['go']['handlers']['SettingsHandler']['SkipVersion'](arg1);
}

export function Startup(arg1) {
  return window['go']['handlers']['SettingsHandler']['Startup'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['handlers']['SettingsHandler']['UpdatePreferences'](arg1);
}

export function VerifyAdminPin(arg1) {
  return window['go']['handlers']['SettingsHandler']['VerifyAdminPin'](arg1);
}
