// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateByPIN(arg1) {
  return window['go']['handlers']['StaffHandler']['AuthenticateByPIN'](arg1);
}

export function AuthenticateByUsername(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['AuthenticateByUsername'](arg1, arg2);
}

export function CreateStaff(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['CreateStaff'](arg1, arg2);
}

export function DeleteStaff(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['DeleteStaff'](arg1, arg2);
}

export function GetActiveStaff() {
  return window['go']['handlers']['StaffHandler']['GetActiveStaff']();
}

export function GetAllStaff() {
  return window['go']['handlers']['StaffHandler']['GetAllStaff']();
}

export function GetStaff(arg1) {
  return window['go']['handlers']['StaffHandler']['GetStaff'](arg1);
}

export function GetStaffCount() {
  return window['go']['handlers']['StaffHandler']['GetStaffCount']();
}

export function HasPermission(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['HasPermission'](arg1, arg2);
}

export function IsUsingDefaultPassword(arg1) {
  return window['go']['handlers']['StaffHandler']['IsUsingDefaultPassword'](arg1);
}

export function Logout() {
  return window['go']['handlers']['StaffHandler']['Logout']();
}

export function Startup(arg1) {
  return window['go']['handlers']['StaffHandler']['Startup'](arg1);
}

export function ToggleStaffStatus(arg1) {
  return window['go']['handlers']['StaffHandler']['ToggleStaffStatus'](arg1);
}

export function UpdateStaff(arg1) {
  return window['go']['handlers']['StaffHandler']['UpdateStaff'](arg1);
}

export function UpdateStaffPIN(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['UpdateStaffPIN'](arg1, arg2);
}

export function UpdateStaffPassword(arg1, arg2) {
  return window['go']['handlers']['StaffHandler']['UpdateStaffPassword'](arg1, arg2);
}
