// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AuthenticateByPIN(arg1:string):Promise<domain.AuthResult>;

export function AuthenticateByUsername(arg1:string,arg2:string):Promise<domain.AuthResult>;

export function CreateStaff(arg1:domain.Staff,arg2:string):Promise<domain.Staff>;

export function DeleteStaff(arg1:string,arg2:boolean):Promise<void>;

export function GetActiveStaff():Promise<Array<domain.Staff>>;

export function GetAllStaff():Promise<Array<domain.Staff>>;

export function GetStaff(arg1:string):Promise<domain.Staff>;

export function GetStaffCount():Promise<number>;

export function HasPermission(arg1:string,arg2:string):Promise<boolean>;

export function IsUsingDefaultPassword(arg1:string):Promise<boolean>;

export function Logout():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleStaffStatus(arg1:string):Promise<void>;

export function UpdateStaff(arg1:domain.Staff):Promise<void>;

export function UpdateStaffPIN(arg1:string,arg2:string):Promise<void>;

export function UpdateStaffPassword(arg1:string,arg2:string):Promise<void>;
