// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function GetDashboardStats(arg1:string):Promise<domain.DashboardStats>;

export function GetMonthlyComparison():Promise<domain.MonthlyComparison>;

export function Startup(arg1:context.Context):Promise<void>;
