// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardStats(arg1) {
  return window['go']['handlers']['StatsHandler']['GetDashboardStats'](arg1);
}

export function GetMonthlyComparison() {
  return window['go']['handlers']['StatsHandler']['GetMonthlyComparison']();
}

export function Startup(arg1) {
  return window['go']['handlers']['StatsHandler']['Startup'](arg1);
}
