//go:build windows

package secureconfig

import (
	"fmt"

	"golang.org/x/sys/windows/registry"
)

// readMachineGuidFromRegistry reads the Cryptography\\MachineGuid value from
// the local machine registry. This GUID is generated by Windows at install
// time and is a stable per-machine identifier.
func readMachineGuidFromRegistry() (string, error) {
	k, err := registry.OpenKey(registry.LOCAL_MACHINE, `SOFTWARE\Microsoft\Cryptography`, registry.QUERY_VALUE|registry.WOW64_64KEY)
	if err != nil {
		return "", fmt.Errorf("open cryptography key: %w", err)
	}
	defer k.Close()

	guid, _, err := k.GetStringValue("MachineGuid")
	if err != nil {
		return "", fmt.Errorf("read MachineGuid: %w", err)
	}
	return guid, nil
}
