// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AI_GenerateStream(arg1) {
  return window['go']['main']['App']['AI_GenerateStream'](arg1);
}

export function CalculateInstallmentPlan(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateInstallmentPlan'](arg1, arg2, arg3);
}

export function DownloadProductsTemplateNative() {
  return window['go']['main']['App']['DownloadProductsTemplateNative']();
}

export function ExportDatabaseBackupNative() {
  return window['go']['main']['App']['ExportDatabaseBackupNative']();
}

export function ExportProductsCSV() {
  return window['go']['main']['App']['ExportProductsCSV']();
}

export function ExportProductsCSVNative() {
  return window['go']['main']['App']['ExportProductsCSVNative']();
}

export function GetBackupConfig() {
  return window['go']['main']['App']['GetBackupConfig']();
}

export function GetCSVTemplate() {
  return window['go']['main']['App']['GetCSVTemplate']();
}

export function GetInstallmentAlertSummary() {
  return window['go']['main']['App']['GetInstallmentAlertSummary']();
}

export function ImportDatabaseBackupNative() {
  return window['go']['main']['App']['ImportDatabaseBackupNative']();
}

export function ImportProductsCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportProductsCSV'](arg1, arg2);
}

export function ImportProductsCSVNative(arg1) {
  return window['go']['main']['App']['ImportProductsCSVNative'](arg1);
}

export function SetCloudAutoSync(arg1) {
  return window['go']['main']['App']['SetCloudAutoSync'](arg1);
}
