// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceCloseApp() {
  return window['go']['main']['App']['ForceCloseApp']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}
