// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AI_CancelStream():Promise<void>;

export function AI_GenerateStream(arg1:string):Promise<void>;

export function CalculateInstallmentPlan(arg1:domain.Amount,arg2:domain.Amount,arg3:number):Promise<domain.InstallmentPlan>;

export function DownloadProductsTemplateNative():Promise<boolean>;

export function ExportDatabaseBackupNative():Promise<boolean>;

export function ExportProductsCSV():Promise<domain.CSVExportResult>;

export function ExportProductsCSVNative():Promise<domain.CSVExportResult>;

export function ForceQuit():Promise<void>;

export function GetBackupConfig():Promise<domain.BackupConfig>;

export function GetCSVTemplate():Promise<string>;

export function GetInstallmentAlertSummary():Promise<Record<string, any>>;

export function ImportDatabaseBackupNative():Promise<boolean>;

export function ImportProductsCSV(arg1:string,arg2:boolean):Promise<domain.CSVImportResult>;

export function ImportProductsCSVNative(arg1:boolean):Promise<domain.CSVImportResult>;

export function MinimizeWindow():Promise<void>;

export function SetCloudAutoSync(arg1:boolean):Promise<void>;
